rem  JLaunchPad config properties (user)

SET DRIVE_LETTER=c:

SET PROXY_SERVER_HOST_NAME=
SET PROXY_SERVER_PORT=
SET PROXY_USER=
SET PROXY_PASSWORD=

SET JAVA_HOME=%DRIVE_LETTER%\Java\jdk1.5.0
