rem config.bat

rem Default values
SET DRIVE_LETTER=c:
SET PROXY_SERVER_HOST_NAME=
SET PROXY_SERVER_PORT=
SET PROXY_USER=
SET PROXY_PASSWORD=

SET DEBUG_MODE=false

SET JAVA_HOME=%DRIVE_LETTER%\Java\jdk1.6.0
SET JLAUNCHPAD_HOME=%DRIVE_LETTER%\jlaunchpad
SET REPOSITORY_HOME=%DRIVE_LETTER%\maven-repository

rem Constants
SET JAVA_SPECIFICATION_VERSION_LEVEL=1.5
SET JLAUNCHPAD_VERSION=1.0.1
SET CLASSWORLDS_VERSION=1.1
SET JDOM_VERSION=1.1
SET BOOTSTRAP_MINI_VERSION=2.0.8

rem Overwrites default values, if exists
IF EXIST %USERPROFILE%\jlaunchpad\config.bat (
  @call "%USERPROFILE%\jlaunchpad\config.bat"
) else (
  @call "%~dp0user\config.bat"
)

IF NOT EXIST %JAVA_HOME% (
  ECHO JDK cannot be found!
  PAUSE
  EXIT
)

rem System properties
SET SYSTEM_PROPERTIES="-Djlaunchpad.home=%JLAUNCHPAD_HOME%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Drepository.home=%REPOSITORY_HOME%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Djlaunchpad.version=%JLAUNCHPAD_VERSION%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Dclassworlds.version=%CLASSWORLDS_VERSION%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Djdom.version=%JDOM_VERSION%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Dbootstrap-mini.version=%BOOTSTRAP_MINI_VERSION%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Djava.specification.version.level=%JAVA_SPECIFICATION_VERSION_LEVEL%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Djava.home.internal=%JAVA_HOME%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Ddebug.mode=%DEBUG_MODE%"

IF NOT "%PROXY_SERVER_HOST_NAME" == "" (
  SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-DproxySet=true" "-DproxyHost=%PROXY_SERVER_HOST_NAME%" "-DproxyPort=%PROXY_SERVER_PORT%"
  SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-DproxyUser=%PROXY_USER%" "-DproxyPassword=%PROXY_PASSWORD%"
)
