#!/bin/sh

# Default values

JAVA_HOME=~/jdk1.6.0_03

if [ ! -e $JAVA_HOME ]; then
  echo "JDK cannot be found!"
  
  return
fi

DEBUG_MODE=false
CYGWIN=false

# Constants

JAVA_SPECIFICATION_VERSION_LEVEL=1.5
JLAUNCHPAD_VERSION=1.0.3
CLASSWORLDS_VERSION=1.1
JDOM_VERSION=1.1
BOOTSTRAP_MINI_VERSION=2.0.9

# System properties

SYSTEM_PROPERTIES="-Djlaunchpad.version=$JLAUNCHPAD_VERSION \
-Dclassworlds.version=$CLASSWORLDS_VERSION \
-Djdom.version=$JDOM_VERSION \
-Dbootstrap-mini.version=$BOOTSTRAP_MINI_VERSION \
-Djava.specification.version.level=$JAVA_SPECIFICATION_VERSION_LEVEL \
-Djava.home.internal=$JAVA_HOME \
-Ddebug.mode=$DEBUG_MODE"

export PROXY_SERVER_HOST_NAME PROXY_SERVER_PORT
export JAVA_HOME JLAUNCHPAD_HOME REPOSITORY_HOME
export JAVA_SPECIFICATION_VERSION_LEVEL JLAUNCHPAD_VERSION
export SYSTEM_PROPERTIES

